//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta_catering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oferta_catering()
        {
            this.Szablon_uroczystości = new HashSet<Szablon_uroczystości>();
        }
    
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public decimal Cena { get; set; }
        public int Ilosc_dan { get; set; }
        public decimal Oferta_catering_ID { get; set; }
        public decimal Podwykonawca_Podwykonawca_ID { get; set; }
    
        public virtual Podwykonawca Podwykonawca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szablon_uroczystości> Szablon_uroczystości { get; set; }
    }
}
