//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podwykonawca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podwykonawca()
        {
            this.Oferta_catering = new HashSet<Oferta_catering>();
            this.Oferta_cukiernik = new HashSet<Oferta_cukiernik>();
            this.Oferta_kwiaciarnia = new HashSet<Oferta_kwiaciarnia>();
        }
    
        public string Nazwa { get; set; }
        public string Adres { get; set; }
        public int Nr_telefonu { get; set; }
        public decimal Podwykonawca_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_catering> Oferta_catering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_cukiernik> Oferta_cukiernik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_kwiaciarnia> Oferta_kwiaciarnia { get; set; }
    }
}
