//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        public System.DateTime Data_podpisania { get; set; }
        public decimal Cena_calkowita { get; set; }
        public decimal Status_Status_ID { get; set; }
        public decimal Wesele_Wesele_ID { get; set; }
        public decimal Klient_Osoba_Osoba_ID { get; set; }
        public int Umowa_ID1 { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Status Status { get; set; }
        public virtual Wesele Wesele { get; set; }
    }
}
