//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MASEntities : DbContext
    {
        public MASEntities()
            : base("name=MASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lokalizacja> Lokalizacjas { get; set; }
        public virtual DbSet<Oferta_catering> Oferta_catering { get; set; }
        public virtual DbSet<Oferta_cukiernik> Oferta_cukiernik { get; set; }
        public virtual DbSet<Oferta_kwiaciarnia> Oferta_kwiaciarnia { get; set; }
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Konsultant> Konsultants { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Podwykonawca> Podwykonawcas { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Szablon_uroczystości> Szablon_uroczystości { get; set; }
        public virtual DbSet<Wesele> Weseles { get; set; }
        public virtual DbSet<Umowa> Umowas { get; set; }
    }
}
